In [1]:
import numpy as np
import pandas as pd

In [2]:
# question_row = [
#     "2,2",
#     "2,2",
#     "4",
#     "2",
#     "4",
#     "4",
#     "2,2",
#     "4,4",
#     "1,1,1,1",
#     "3,3"
# ]

# question_col = [
#     "3",
#     "1,1,1",
#     "2,4",
#     "2,4",
#     "4",
#     "4",
#     "2,4",
#     "2,4",
#     "1,1,1",
#     "3"
# ]

In [3]:
# https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=sangseungedu&logNo=221543957659
question_row = [
    "4,1",
    "5",
    "2,3",
    "2,1",
    "1,2",
    "1,1",
]

question_col = [
    "1,3",
    "4",
    "2,2",
    "5",
    "2",
    "3,1",
]

In [4]:
df = pd.DataFrame(index=np.array(question_row),columns=np.array(question_col))
df.fillna('?',inplace=True)
df

    1,3  4 2,2  5  2 3,1
4,1   ?  ?   ?  ?  ?   ?
5     ?  ?   ?  ?  ?   ?
2,3   ?  ?   ?  ?  ?   ?
2,1   ?  ?   ?  ?  ?   ?
1,2   ?  ?   ?  ?  ?   ?
1,1   ?  ?   ?  ?  ?   ?

In [91]:
# def reverse(data,where):
#     assert where in ['row','col'],\
#         "where must be in ['row','col']"
    
#     if where=='col':
#         data = data.T
        
#     reverse_question_list = []
#     reverse_answer_list = []
#     for question,answer in zip(data.index,data.values):
#         question_list = question.split(',')
#         reverse_question = ','.join(question_list[::-1])
#         reverse_answer = answer[::-1]
        
#         reverse_question_list.append(reverse_question)
#         reverse_answer_list.append(reverse_answer)
    
#     reverse_answer_list = np.array(reverse_answer_list)
#     reverse_column_list = data.columns[::-1]
#     reverse_data = pd.DataFrame(reverse_answer_list,index=reverse_question_list,columns=reverse_column_list)
#     if where=='col':
#         return reverse_data.T
#     else:
#         return reverse_data

In [ ]:
# test = pd.DataFrame(np.array(range(36)).reshape(6,6),index=df.index,columns=df.columns)
# display(test)

# reverse(data=test,where='row')

In [637]:
#------------------------------------------------------------------#
# fn1. 정답확인 - O랑 ?의 합이 question의 합과 같은 경우에, ?를 O로 넣기
# ex. question : (1,2)
#     answer   : (O,X,?,O,X)
#     ->
#     answer   : (O,X,O,O,X)
#------------------------------------------------------------------#
def complete(questions,answers):
    new_answers = []
    for question,answer in zip(questions,answers):
        question_list = [int(x) for x in question.split(',')]
        new_answer = answer.copy()

        n_o       = np.where(np.array(new_answer)=='O',1,0).sum()
        n_x       = np.where(np.array(new_answer)=='X',1,0).sum()
        n_unknown = np.where(np.array(new_answer)=='?',1,0).sum()
        if n_o+n_unknown==sum(question_list):
            new_answer = [a.replace('?','O') for a in new_answer]
            new_answers.append(new_answer)
        else:
            new_answers.append(new_answer)
    return new_answers

#------------------------------------------------------------------#
# fn2. 정답나온뒤에 X넣기
# ex. question : (1,1)
#     answer   : (O,?,?,?,?)
#     ->
#     answer   : (O,X,?,?,?)
#------------------------------------------------------------------#
def add_block(questions,answers):
    new_answers = []
    for question,answer in zip(questions,answers):
        question_list = [int(x) for x in question.split(',')]
        new_answer = answer.copy()

        q_i=0
        start=0
        for a_i in range(len(new_answer)):
            target = new_answer[start:a_i+1]
            n_o       = np.where(np.array(target)=='O',1,0).sum()
            n_unknown = np.where(np.array(target)=='?',1,0).sum()
            
            # 마지막에왔는데 ['X']를 하나 더 더하면 length가 +1되서 맞지않음
            if q_i+1==len(question_list):
                pass
            # (1) O의 개수가 question이랑 같을때
            # (2) 마지막이 아닌 경우
            # (3) "?"가 없는 경우
            elif (n_o==question_list[q_i]) & (a_i+1!=len(new_answer)) & (n_unknown==0):
                new_answer = list(new_answer[:start]) + list(target) + ['X'] + list(new_answer[a_i+2:])
                q_i+=1
                start=a_i+1
            else:
                pass
            
        new_answers.append(new_answer)
    return new_answers

#------------------------------------------------------------------#
# fn3. 정답나온뒤에 O넣기
# ex. question : (2,1)
#     answer   : (O,?,X,X,?)
#     ->
#     answer   : (O,O,X,X,O)
#------------------------------------------------------------------#
def add_ox(questions,answers):
    new_answers = []
    for question,answer in zip(questions,answers):
        question_list = [int(x) for x in question.split(',')]
        new_answer = answer.copy()

        # X개수확인
        n_o = np.where(np.array(new_answer)=='O',1,0).sum()
        n_x = np.where(np.array(new_answer)=='X',1,0).sum()
        n_unknown = np.where(np.array(new_answer)=='?',1,0).sum()
        n_check = len(answer)-sum(question_list)-1
        
        # (1) X가 다 입력되어있고,
        #     O,?의 합이 question이랑 같으면, ?를 O로 넣기
        if (n_x==n_check) & (n_o+n_unknown==sum(question_list)):
            new_answer = [a.replace('?','O') for a in new_answer]
        
        # (2) O가 다 입력되어있으면, ?를 X로 넣기
        if n_o==sum(question_list):
            new_answer = [a.replace('?','X') for a in new_answer]
            
        new_answers.append(new_answer)

    return new_answers

#------------------------------------------------------------------#
# fn4. 앞에 ?가 없고, 연속되는 O 뒤에 ?가 있으면 -> question이랑 비교해서 정답맞추기
# ex. question : (1,3)
#     answer   : (O,X,O,O,?)
#     ->
#     answer   : (O,X,O,O,O)
#------------------------------------------------------------------#
def add_o(questions,answers):
    new_answers = []
    check_i=0
    for question,answer in zip(questions,answers):
        check_i+=1
        question_list = [int(x) for x in question.split(',')]
        new_answer = answer.copy()
        
        # (1) ?가 없으면 pass
        if np.where(np.array(new_answer)=='?',1,0).sum()==0:
            new_answers.append(new_answer)
        else:
            q_i=0
            repeat_o_cnt = 0
            repeat_u_cnt = 0
            repeat_o_cnt_last = 0
            repeat_u_cnt_last = 0

            for a_i in range(len(new_answer)):

                # 반복되는 o,?의 개수 세기
                if new_answer[a_i]=='O':
                    repeat_o_cnt+=1
                    repeat_o_cnt_last = repeat_u_cnt # O로바뀌면 연속?의개수의 기록사라지니까 저장
                    repeat_u_cnt=0
                elif new_answer[a_i]=='?':
                    repeat_u_cnt+=1
                    repeat_o_cnt_last = repeat_o_cnt # ?로바뀌면 연속O의개수의 기록사라지니까 저장
                    repeat_o_cnt=0
                else:
                    repeat_o_cnt_last = repeat_o_cnt
                    repeat_u_cnt_last = repeat_u_cnt
                    repeat_o_cnt=0
                    repeat_u_cnt=0

                # (2) O가 나오기도전에 ?가 나오면 break
                if (new_answer[a_i]=='?') & (repeat_o_cnt_last==0):
                    break
                # (3) X가 나오면 pass
                elif new_answer[a_i]=='X':
                    pass
                # 질문범위벗어나면 break
                elif q_i+1>len(question_list):
                    pass
                # (4) O가 나왔는데 해당iter의 question에 맞으면, 다음iter로 넘기기
                elif (new_answer[a_i]=='O') & (repeat_o_cnt==question_list[q_i]):
                    q_i+=1
                # (5) ?가 나왔는데, 다음 question이 없는 경우에 O로 넣기
                elif (new_answer[a_i]=='?') & (q_i+1==len(question_list)):
                    #print('changed')
                    new_answer = new_answer[:a_i] + ['O'] + new_answer[a_i+1:]
                else:
                    pass

                # if check_i==5:
                #     check_1 = len(question_list)==q_i+2
                #     check_2 = repeat_o_cnt==question_list[q_i]
                #     print('new_answer:',new_answer)
                #     print('new_answer[a_i]:',new_answer[a_i])
                #     print('q_i:',q_i)
                #     print('check_1:',check_1)
                #     print('check_2:',check_2)
                #     print('')

            new_answers.append(new_answer)
    return new_answers

def update(data,where):
    assert where in ['row','col'],\
        "where must be in ['row','col']"

    # col인 경우, transpose를 통해 row로 변경
    # -> 마지막에 다시 transpose를 통해 col로 변경
    if where=='col':
        data = data.T
    
    # 행 기준으로 작성
    tobe_answer = []
    for i in range(len(data)):
        # question, answer 입력
        question = data.index[i].split(',')
        answer   = data.iloc[i,:].values

        #------------------------------------------------------------------#
        # (1) 좌우에서, 시작부터 "O"가 연속인 것들 제거해서 정답찾기
        # ex. question : (2,2)
        #     answer   : (O,O,?,?,?)
        #     -> 
        #     question : (2)
        #     answer   : (X,?,?)
        #------------------------------------------------------------------#
        # (1-1) 반복되는 "0"이 끝나는지점 찾기 (start,end)
        # 왼쪽부터
        for start in range(len(answer)):
            if answer[start]!='O':
                break
            else:
                pass
        # 오른쪽부터
        for end in range(len(answer)):
            if answer[-end-1]!='O':
                break
            else:
                pass

        # (1-2) ~start,end~가 제외되는 새로운 answer생성
        #       ~start,end~는 따로 저장
        if end==0:
            new_answer = answer[start:]
            new_answer_left_prefix  = answer[:start]
            new_answer_right_prefix = np.array([])
        else:
            new_answer = answer[start:-end-1]
            new_answer_left_prefix  = answer[:start]
            new_answer_right_prefix = answer[-end-1:]
        
        # (1-3) 연속된 "O"를 뺐으므로, 질문을 수정 (왼쪽에만 영향을 주므로, 왼쪽만 변경)
        # [1] 첫번째 질문은 이미 맞춘 경우에, 첫번째 질문을 제외
        #     + 답변의 맨 첫번째값은 "X"로 넣기
        if int(question[0])==len(new_answer_left_prefix):
            question = question[1:]
            if len(new_answer)>0:
                new_answer[0] = "X"
        # [2] 연속된 "O"가 빠진 만큼, 정답의 개수를 줄이기
        elif int(question[0])>len(new_answer_left_prefix):
            question[0] = str(int(question[0])-len(new_answer_left_prefix))
        else:
            pass
        
        #------------------------------------------------------------------#
        # (2) 수식을 근거로 "O"가 확정적인 대상들 찾기
        #     -> 좌우로 모르는 개수 = 열의개수 - (질문의합 + 질문의개수 - 1)
        #------------------------------------------------------------------#
        # 좌우로 모르는 개수
        n_unknown = sum([int(q) for q in question]) + len(question) - 1
        n_unknown = len(new_answer) - n_unknown

        # (2-1) (1-3)에서 question이 제외되어 질문이 모두 사라진 경우
        #       -> 정답을 모두 맞췄으므로 더이상 할 필요가 없음
        if len(question)==0:
            tobe_answer.append(answer)
        
        # (2-2) 모르는 개수가 없는 경우에는 question 자체가 답이므로, question을 answer로 넣기
        elif n_unknown==0:
            new_answer = []
            for q_i,q in enumerate(question):
                new_answer+=['O']*int(q)
                if q_i+1!=len(question):
                    new_answer+=['X']
                else:
                    pass
            new_answer = new_answer_left_prefix.tolist() + new_answer + new_answer_right_prefix.tolist()
            tobe_answer.append(new_answer)

        # (2-3) 모르는 개수가 있는 경우
        else:
            # 순서 생성
            new_answer_idx = [a_i for a_i in range(len(new_answer))]

            # [모르는거], [아는거], [모르는거], [아는거], [모르는거]
            unknown_left_idx   = new_answer_idx[:n_unknown]
            known_left_idx     = new_answer_idx[n_unknown:int(question[0])]
            unknown_middle_idx = new_answer_idx[int(question[0]):len(new_answer)-int(question[-1])]
            known_right_idx    = new_answer_idx[len(new_answer)-int(question[-1]):-n_unknown]
            unknown_right_idx  = new_answer_idx[-n_unknown:]

            # 아는거/모르는거 각각 인덱스합치기
            unknown_idx = unknown_left_idx+unknown_middle_idx+unknown_right_idx
            known_idx   = known_left_idx+known_right_idx

            # 중복제거
            unknown_idx = sorted(pd.unique(unknown_idx))
            known_idx   = sorted(pd.unique(known_idx))

            # "O","X"인 경우에는 그대로 넣고,
            # 수식에 의해 아는거인 경우에는 "O"로 넣고,
            # 모르는거면 "?"로 넣기
            new_answer = ['O' if new_answer[idx_i]=='O' else  # 이미 "O"면 건드리지 않도록 설정
                          'X' if new_answer[idx_i]=='X' else
                          'O' if idx_i in known_idx else
                          '?' if idx_i in unknown_idx else
                          'ERROR' for idx_i in range(len(new_answer))]
            new_answer = new_answer_left_prefix.tolist() + new_answer + new_answer_right_prefix.tolist()

            # final append
            tobe_answer.append(new_answer)
            
    #------------------------------------------------------------------#
    # (3) 정답확인
    #------------------------------------------------------------------#
    tobe_answer2 = tobe_answer.copy()
    
    tobe_answer2 = complete(questions=data.index,answers=tobe_answer2)
    tobe_answer2 = add_block(questions=data.index,answers=tobe_answer2)
    tobe_answer2 = add_ox(questions=data.index,answers=tobe_answer2)
    tobe_answer2 = add_o(questions=data.index,answers=tobe_answer2)
    
    tobe_answer2 = np.array(tobe_answer2).T.tolist()
    tobe_answer2 = complete(questions=data.T.index,answers=tobe_answer2)
    tobe_answer2 = add_block(questions=data.T.index,answers=tobe_answer2)
    tobe_answer2 = add_ox(questions=data.T.index,answers=tobe_answer2)
    tobe_answer2 = add_o(questions=data.T.index,answers=tobe_answer2)
    tobe_answer2 = np.array(tobe_answer2).T.tolist()
            
    #------------------------------------------------------------------#
    # (4) "O"랑 "?"로 question을 맞출 수 있는 경우에, "?"를 "O"로 채워넣기
    # ex. question : (2,1)
    #     answer   : (O,?,X,O,X)
    #     ->
    #     answer   : (O,O,X,O,X)
    #------------------------------------------------------------------#
    tobe_answer3 = []
    for question,answer in zip(data.index,tobe_answer2):
        question_list = [int(x) for x in question.split(',')]
        new_answer = answer.copy()

        # 시작이 ?이면 pass
        if new_answer[0]=='?':
            tobe_answer3.append(new_answer)
        else:
            q_i = 0
            start = 0
            for a_i in range(len(new_answer)):
                target = new_answer[start:a_i+1]
                n_o       = np.where(np.array(target)=='O',1,0).sum()
                n_unknown = np.where(np.array(target)=='?',1,0).sum()

                # 마지막에왔는데 ['X']를 하나 더 더하면 length가 +1되서 맞지않음
                if q_i+1==len(question_list):
                    pass
                elif n_o+n_unknown==question_list[q_i]:
                    target = [t.replace('?','O') for t in target]
                    new_answer = new_answer[:start] + target + ['X'] + new_answer[a_i+2:]
                    q_i+=1
                    start=a_i+1
                else:
                    pass

            tobe_answer3.append(new_answer)
    
    #------------------------------------------------------------------#
    # (5) 정답확인
    #------------------------------------------------------------------#
    tobe_answer4 = tobe_answer3.copy()
    
    tobe_answer4 = complete(questions=data.index,answers=tobe_answer4)
    tobe_answer4 = add_block(questions=data.index,answers=tobe_answer4)
    tobe_answer4 = add_o(questions=data.index,answers=tobe_answer4)
    tobe_answer4 = add_o(questions=data.index,answers=tobe_answer4)
    
    tobe_answer4 = np.array(tobe_answer4).T.tolist()
    tobe_answer4 = complete(questions=data.T.index,answers=tobe_answer4)
    tobe_answer4 = add_block(questions=data.T.index,answers=tobe_answer4)
    tobe_answer4 = add_o(questions=data.T.index,answers=tobe_answer4)
    tobe_answer4 = add_o(questions=data.T.index,answers=tobe_answer4)
    tobe_answer4 = np.array(tobe_answer4).T.tolist()

                
    tobe_answer5 = tobe_answer4.copy()
    # col이면 T해서 return
    if where=='col':
        result = np.array(tobe_answer5).T.tolist()
        result = pd.DataFrame(result,index=data.T.index,columns=data.T.columns)
    else:
        result = tobe_answer5
        result = pd.DataFrame(result,index=data.index,columns=data.columns)
    
    return result

In [638]:
n_trial = 5
df_new = df.copy()

for k in range(1,n_trial+1):
    df_new = update(data=df_new,where='row')
    df_new = update(data=df_new,where='col')

In [639]:
df_new

    1,3  4 2,2  5  2 3,1
4,1   O  O   O  O  X   O
5     X  O   O  O  O   O
2,3   O  O   X  O  O   O
2,1   O  O   X  O  X   X
1,2   O  X   O  O  X   X
1,1   X  X   O  X  X   O

In [595]:
question=df_new.index[1]
answer=df_new.values.tolist()[1]
question,answer

('5', ['X', 'O', 'O', 'O', 'O', 'O'])

In [529]:
df_new

    1,3  4 2,2  5  2 3,1
4,1   O  O   O  O  X   O
5     X  O   O  O  O   O
2,3   O  O   X  O  O   O
2,1   O  O   X  O  X   X
1,2   ?  X   O  O  X   ?
1,1   ?  X   O  X  X   ?

In [629]:
#------------------------------------------------------------------#
# fn4. 앞에 ?가 없고, 연속되는 O 뒤에 ?가 있으면 -> question이랑 비교해서 정답맞추기
# ex. question : (1,3)
#     answer   : (O,X,O,O,?)
#     ->
#     answer   : (O,X,O,O,O)
#------------------------------------------------------------------#
def add_o(questions,answers):
    new_answers = []
    check_i=0
    for question,answer in zip(questions,answers):
        check_i+=1
        question_list = [int(x) for x in question.split(',')]
        new_answer = answer.copy()
        
        # (1) ?가 없으면 pass
        if np.where(np.array(new_answer)=='?',1,0).sum()==0:
            new_answers.append(new_answer)
        else:
            q_i=0
            repeat_o_cnt = 0
            repeat_u_cnt = 0
            repeat_o_cnt_last = 0
            repeat_u_cnt_last = 0

            for a_i in range(len(new_answer)):

                # 반복되는 o,?의 개수 세기
                if new_answer[a_i]=='O':
                    repeat_o_cnt+=1
                    repeat_o_cnt_last = repeat_u_cnt # O로바뀌면 연속?의개수의 기록사라지니까 저장
                    repeat_u_cnt=0
                elif new_answer[a_i]=='?':
                    repeat_u_cnt+=1
                    repeat_o_cnt_last = repeat_o_cnt # ?로바뀌면 연속O의개수의 기록사라지니까 저장
                    repeat_o_cnt=0
                else:
                    repeat_o_cnt_last = repeat_o_cnt
                    repeat_u_cnt_last = repeat_u_cnt
                    repeat_o_cnt=0
                    repeat_u_cnt=0

                # (2) O가 나오기도전에 ?가 나오면 break
                if (new_answer[a_i]=='?') & (repeat_o_cnt_last==0):
                    break
                # (3) X가 나오면 pass
                elif new_answer[a_i]=='X':
                    pass
                # (4) O가 나왔는데 해당iter의 question에 맞으면, 다음iter로 넘기기
                elif (new_answer[a_i]=='O') & (repeat_o_cnt==question_list[q_i]):
                    q_i+=1
                    # 질문범위벗어나면 break
                    if q_i+2==len(question_list):
                        break
                # (5) ?가 나왔는데, 다음 question이 없는 경우에 O로 넣기
                elif (new_answer[a_i]=='?') & (q_i+1==len(question_list)):
                    #print('changed')
                    new_answer = new_answer[:a_i] + ['O'] + new_answer[a_i+1:]
                else:
                    pass

                # if check_i==5:
                #     check_1 = len(question_list)==q_i+2
                #     check_2 = repeat_o_cnt==question_list[q_i]
                #     print('new_answer:',new_answer)
                #     print('new_answer[a_i]:',new_answer[a_i])
                #     print('q_i:',q_i)
                #     print('check_1:',check_1)
                #     print('check_2:',check_2)
                #     print('')

            new_answers.append(new_answer)
    return new_answers

In [630]:
add_o(df_new.T.index,df_new.T.values.tolist())

check_i: 1, a_i: 0, q_i: 0, if_3 passed
check_i: 1, a_i: 1, q_i: 1, if_2 passed
check_i: 1, a_i: 2, q_i: 1, if_5 passed
check_i: 1, a_i: 3, q_i: 1, if_5 passed
check_i: 1, a_i: 4, q_i: 1, if_4 passed
changed
check_i: 1, a_i: 5, q_i: 1, if_1 passed
check_i: 6, a_i: 0, q_i: 0, if_5 passed
check_i: 6, a_i: 1, q_i: 0, if_5 passed
check_i: 6, a_i: 2, q_i: 0, if_3 passed
check_i: 6, a_i: 3, q_i: 1, if_2 passed
check_i: 6, a_i: 4, q_i: 1, if_1 passed

[['O', 'X', 'O', 'O', 'O', '?'],
 ['O', 'O', 'O', 'O', 'X', 'X'],
 ['O', 'O', 'X', 'X', 'O', 'O'],
 ['O', 'O', 'O', 'O', 'O', 'X'],
 ['X', 'O', 'O', 'X', 'X', 'X'],
 ['O', 'O', 'O', 'X', '?', '?']]

In [614]:
df_new.T

    4,1  5 2,3 2,1 1,2 1,1
1,3   O  X   O   O   ?   ?
4     O  O   O   O   X   X
2,2   O  O   X   X   O   O
5     O  O   O   O   O   X
2     X  O   O   X   X   X
3,1   O  O   O   X   ?   ?